"""init_schema

Revision ID: 5ad10ff4938f
Revises: 
Create Date: 2026-07-12 13:22:16.861798

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '5ad10ff4938f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
